### PR TITLE
Fixed zero sized payloads and overloading enum cases issues

### LINKED ISSUE #4: func decompose() returns nil for associated values of zero size
Hi, I've come across a bit of an edge-case:
```
struct ExampleView: View {
    var body: some View {
        EmptyView()
    }
}
enum MyClosedSetOfViews {
    case example(ExampleView)
}

let value = MyClosedSetOfViews.example(ExampleView())
value[case: MyClosedSetOfViews.example] // == nil
```

I've briefly experimented in a fork, adding in a few tests (which fail as expected), but as far as I can tell this is a limitation in the Mirror API which can only be worked around by padding the case with an additional associated value of non-zero size.

The root cause of the problem is that the return children array of Mirror is empty, so this looks like a Swift language bug, but I'd like to open this issue in case anyone can find a viable fix that I've overlooked.

### PR DESCRIPTION
**Pull request by gringoireDM**
Fixes https://github.com/gringoireDM/EnumKit/issues/4
This PR also fixes overloading enum cases

```swift
enum Mock: CaseAccessible {
    case foo(Int)
    case foo(anInt: Int)
    case foo(anInt: Int, andAString: String)
}
```

is now possible to use.

`enumCase[case: { Mock.foo($0) }]`
`enumCase[case: Mock.foo(anInt:)]`
`enumCase[case: Mock.foo(anInt: andAString:)]`

### CODE REVIEW

File: Sources/EnumKit/Core/CaseAccessible.swift [hunk 1]
```diff
@@ -18,8 +18,9 @@ public extension CaseAccessible {
     
     /// Check if an enum case matches another case
     func matches(case: Self) -> Bool {
-        let targetStr = `case`.label
-        return label == targetStr
+        var root = self
+        var `case` = `case`
+        return memcmp(&root, &`case`, MemoryLayout<Self>.size) == 0
```
Comment (MutatingFunc) [inline Sources/EnumKit/Core/CaseAccessible.swift:23]: I'll back this as a robust solution for matching, considering this is the whole enum case and so should have the case index in memory.

File: Sources/EnumKit/Core/CaseAccessible.swift [hunk 2]
```diff
@@ -144,16 +144,23 @@ public extension CaseAccessible {
...
+        guard mirror.displayStyle == .enum else { return nil }
+        
+        var path: [String?] = []
+        var any: Any = self
+        
+        while case let (label?, anyChild)? = Mirror(reflecting: any).children.first {
+            path.append(label)
+            path.append(String(describing: type(of: anyChild)))
+            if let child = anyChild as? AssociatedValue { return (path, child) }
+            any = anyChild
```
Comment (MutatingFunc) [inline Sources/EnumKit/Core/CaseAccessible.swift:159]: This is pretty impressive. Took me some debugging to figure out how and why it works, but it does look like when the SR-12255 fix comes in this will kick in for empty associated values too.

Nice to see the ghost of single-element tuples is alive and well in the reflection system. 👻

File: Sources/EnumKit/Core/CaseAccessible.swift [hunk 3]
```diff
@@ -144,16 +144,23 @@ public extension CaseAccessible {
...
+        }
+        if MemoryLayout<AssociatedValue>.size == 0 {
+            return (["\(self)"], unsafeBitCast((), to: AssociatedValue.self))
```
Comment (MutatingFunc) [inline Sources/EnumKit/Core/CaseAccessible.swift:162]: And for now the code falls through this fallback, which looks to be not strictly type-safe, but the best we're going to get in the meantime. Since we don't know the next Swift version SR-12255 is going to make it into, we can't add unit tests wrapped in a version check.

**Review by MutatingFunc — APPROVED** [review]
Thanks for suggesting I take a look, this is actually very interesting!
